name: Deploy to IUT FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: sftp://webinfo.iutmontp.univ-montp2.fr
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASS }}
        local-dir: ./
        server-dir: /public_html/hello_world_site

