name: Deploy to IUT FTP

on:
  push:
    branches:
      - main

jobs:
  deploy-website:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload files to FTP server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ftpinfo.iutmontp.univ-montp2.fr
        port: 22
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASS }}
        remote_path: /home/ann2/challiase/public_html/hello_world_site
        sftp_only: true

